version: 0.2

env:
  variables:
    AWS_IAM_AUTHENTICATOR_RELEASE_DATE: "2019-08-14"
    AWS_IAM_AUTHENTICATOR_VERSION: "1.13.8"
    LOCAL_BIN: "/usr/local/awscli"
phases:
  install:
    commands:
      - pip3 install awscli --upgrade --user
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - REPOSITORY_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/dev/sample_yargs
      - echo $REPOSITORY_IMAGE_URI:$IMAGE_TAG
  build:
    commands:
      - docker build -t $REPOSITORY_IMAGE_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $APP_SERVER_IMAGE_URI:$IMAGE_TAG
      # - cat .aws/dev/task-def.origin.json | sed -e s@\<IMAGE_NAME\>@$APP_SERVER_IMAGE_URI:$IMAGE_TAG@ > taskdef.json
      # - echo taskdef.json file...
      # - cat taskdef.json
# artifacts:
#   files:
#     - task-def.origin.json
