version: 0.2

env:
  variables:
    AWS_IAM_AUTHENTICATOR_RELEASE_DATE: "2019-08-14"
    AWS_IAM_AUTHENTICATOR_VERSION: "1.13.8"
    LOCAL_BIN: "/usr/local/awscli"
  secrets-manager:
    DOCKERHUB_USER: arn:aws:secretsmanager:ap-northeast-1:776209530557:secret:dev/DockerHub-ICz2Kl:dockerhub_username
    DOCKERHUB_PASS: arn:aws:secretsmanager:ap-northeast-1:776209530557:secret:dev/DockerHub-ICz2Kl:dockerhub_password
phases:
  install:
    commands:
      - pip3 install awscli --upgrade --user
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Node.js version is 16
      - n 16
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region ap-northeast-1)
      - echo Logging in to Docker Hub.
      - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - REPOSITORY_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$REPOSITORY_NAME
      - echo docker tag $REPOSITORY_IMAGE_URI:$IMAGE_TAG
  build:
    commands:
      - echo Docker build tag is $REPOSITORY_IMAGE_URI:$IMAGE_TAG
      - docker build -t $REPOSITORY_IMAGE_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Docker push tag is $REPOSITORY_IMAGE_URI:$IMAGE_TAG
      - docker push $REPOSITORY_IMAGE_URI:$IMAGE_TAG
      - printf '[{"name":"$CONTAINER_NAME","imageUri":"%s"}]' $REPOSITORY_IMAGE_URI:$IMAGE_TAG > imagedefinitions.json
      - echo imagedefinitions.json file...
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
